
services:
  orders-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-api-container
    volumes:
      - ./src/OrderSystem.Api:/app/src/OrderSystem.Api
    ports:
      - "5001:5001" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001  
      - REDIS_CONNECTION=redis:6379 
    depends_on:
      - redis 

    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379" 
    networks:
      - backend
    volumes:
      - redis-data:/data 

networks:
  backend:
    driver: bridge  

volumes:
  redis-data:
    driver: local 